creation_rules:
  - path_regex: dev/*
    encrypted_regex: '[\s\S]+'
    age: age13fdrvwkd2vnlvmmukh3evhh2m3akmnfrefsf6mf7p3mlq7drcs6sfruksf
  - path_regex: prod/*
    encrypted_regex: '[\s\S]+'
    age: age13fdrvwkd2vnlvmmukh3evhh2m3akmnfrefsf6mf7p3mlq7drcs6sfruksf
